name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    # runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: test output
      run: |
        cd src 
        cd AMS
        dotnet restore
        dotnet build 
        dotnet run --project AMSConsole

    - name: create package
      run: |
        cd src 
        cd AMS
        dotnet tool restore
        dotnet pwsh readme.ps1
        dotnet pwsh setVersion.ps1
        dotnet clean  
        dotnet build
        echo 'now pack'
        dotnet pack AMS_Base   -o nugetPackages    --no-build --include-symbols --include-source 
        dotnet pack AMS   -o nugetPackages   --no-build --include-symbols --include-source
        dotnet pack AMSWebAPI  -o nugetPackages --no-build --include-symbols --include-source


    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: AMSNuget_${{github.run_number}}
        path: src/AMS/nugetPackages
        retention-days: 1
  